# Generated by Django 3.1.7 on 2021-09-24 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('mesage', models.TextField()),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Send Date')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Name')),
                ('surname', models.CharField(max_length=250, null=True, verbose_name='Surname')),
                ('instagram', models.URLField(blank=True, max_length=250, null=True, verbose_name='Instagram Url')),
                ('twiter', models.URLField(blank=True, max_length=250, null=True, verbose_name='Twitter Url')),
                ('facebook', models.URLField(blank=True, max_length=250, null=True, verbose_name='Facebook Url')),
                ('github', models.URLField(blank=True, max_length=250, null=True, verbose_name='Github Url')),
                ('gmail', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Mail')),
                ('image', models.ImageField(blank=True, upload_to='Teacher_Image/%Y/%M/%D/')),
                ('information', models.TextField(blank=True, max_length=2000, null=True)),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Time')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teahers',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Course Name')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('category', models.CharField(max_length=250, null=True, verbose_name='Category')),
                ('image', models.ImageField(blank=True, upload_to='Courses_image/%Y/%M/%D/%H/%M/%S', verbose_name='Course Image')),
                ('information', models.TextField(blank=True)),
                ('price', models.IntegerField(null=True, verbose_name='Course Price')),
                ('end_day', models.DateTimeField(verbose_name='Application deadline')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('available', models.BooleanField(default=True, verbose_name='if you are sure')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='polls.teachers')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
