# Generated by Django 3.1.7 on 2021-11-19 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211119_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['-create_date'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='student_comment',
            options={'ordering': ['-date'], 'verbose_name': 'Student', 'verbose_name_plural': 'Student'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'ordering': ['-created_date'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teahers'},
        ),
        migrations.RemoveField(
            model_name='courses',
            name='end_day',
        ),
        migrations.AddField(
            model_name='student_comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
