# Generated by Django 3.1.7 on 2021-11-21 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20211119_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='text_multi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup', models.CharField(max_length=250, verbose_name='Text Head')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='teacher',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_day',
            field=models.IntegerField(null=True, verbose_name='Duration of education'),
        ),
        migrations.AddField(
            model_name='courses',
            name='courses_hours',
            field=models.IntegerField(null=True, verbose_name='Hourse education'),
        ),
        migrations.AddField(
            model_name='courses',
            name='mentor',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True, verbose_name='Mentor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='student_price',
            field=models.IntegerField(null=True, verbose_name='Student Price'),
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.AddField(
            model_name='text_multi',
            name='connect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.courses'),
        ),
    ]
