# Generated by Django 3.1.7 on 2021-11-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20211121_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='standart_price',
            field=models.IntegerField(null=True, verbose_name='Standart Price'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.CharField(help_text='Her Categoryden sonra - qoyun', max_length=250, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='text_multi',
            name='connect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolgu', to='polls.courses'),
        ),
    ]
